# Generated by Django 3.2.8 on 2021-10-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yd_drone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YDFlightMissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='flight_missions/')),
            ],
            options={
                'db_table': 'yd_drone_flight_missions_file',
            },
        ),
    ]
