# Generated by Django 3.2.8 on 2021-10-29 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yd_drone', '0002_ydflightmissionfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='YDMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_mission_file', models.FileField(upload_to='flight_missions/')),
                ('at_create', models.DateTimeField()),
            ],
            options={
                'db_table': 'yd_drone__missions_',
            },
        ),
        migrations.DeleteModel(
            name='YDFlightMissionFile',
        ),
        migrations.AddField(
            model_name='ydlogfile',
            name='at_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
