# Generated by Django 3.2.8 on 2021-10-29 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yd_drone', '0003_auto_20211029_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='ydlogfile',
            name='mission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='yd_drone.ydmission'),
            preserve_default=False,
        ),
    ]
