# Generated by Django 3.2.8 on 2021-10-29 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yd_drone', '0004_ydlogfile_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='ydlogfile',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ydlogfile',
            name='flight_data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ydmission',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ydmission',
            name='mission_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='ydmission',
            table='yd_drone_missions',
        ),
    ]
