# Generated by Django 3.2.8 on 2021-10-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yd_drone', '0005_auto_20211029_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='ydmission',
            name='user_info',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ydmission',
            unique_together={('user_info', 'mission_name')},
        ),
    ]
