# Generated by Django 3.2.8 on 2021-10-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yd_drone', '0006_auto_20211029_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ydlogfile',
            name='flight_data',
            field=models.DateTimeField(),
        ),
    ]
