# Generated by Django 3.2.8 on 2021-10-31 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yd_drone', '0007_alter_ydlogfile_flight_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='YDMissionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetLat', models.DecimalField(decimal_places=9, max_digits=15)),
                ('targetLon', models.DecimalField(decimal_places=9, max_digits=15)),
                ('targetAlt', models.DecimalField(decimal_places=4, max_digits=9)),
                ('targetRadius', models.DecimalField(decimal_places=4, max_digits=9)),
                ('loiterTime', models.IntegerField()),
                ('maxHorizSpeed', models.DecimalField(decimal_places=4, max_digits=9)),
                ('maxVertSpeed', models.DecimalField(decimal_places=4, max_digits=9)),
                ('poiLat', models.DecimalField(decimal_places=9, max_digits=15)),
                ('poiLon', models.DecimalField(decimal_places=9, max_digits=15)),
                ('poiHeading', models.DecimalField(decimal_places=4, max_digits=9)),
                ('poiAltitude', models.DecimalField(decimal_places=4, max_digits=9)),
                ('flags', models.IntegerField()),
                ('photo', models.IntegerField()),
                ('panoSectorsCount', models.IntegerField()),
                ('panoDeltaAngle', models.DecimalField(decimal_places=4, max_digits=9)),
                ('poiPitch', models.DecimalField(decimal_places=4, max_digits=9)),
                ('poiRoll', models.DecimalField(decimal_places=4, max_digits=9)),
                ('type', models.IntegerField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yd_drone.ydmission')),
            ],
            options={
                'db_table': 'yd_drone_mission_point',
            },
        ),
    ]
