# Generated by Django 3.2.8 on 2022-01-22 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YDMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=120)),
                ('user_info', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('flight_mission_file', models.FileField(upload_to='flight_missions/')),
                ('at_create', models.DateTimeField()),
            ],
            options={
                'db_table': 'yd_drone_missions',
                'unique_together': {('user_info', 'mission_name')},
            },
        ),
        migrations.CreateModel(
            name='YDMissionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetLat', models.DecimalField(decimal_places=9, max_digits=15)),
                ('targetLon', models.DecimalField(decimal_places=9, max_digits=15)),
                ('targetAlt', models.DecimalField(decimal_places=4, max_digits=9)),
                ('targetRadius', models.DecimalField(decimal_places=4, max_digits=9)),
                ('loiterTime', models.IntegerField()),
                ('maxHorizSpeed', models.DecimalField(decimal_places=4, max_digits=9)),
                ('maxVertSpeed', models.DecimalField(decimal_places=4, max_digits=9)),
                ('poiLat', models.DecimalField(decimal_places=9, max_digits=15)),
                ('poiLon', models.DecimalField(decimal_places=9, max_digits=15)),
                ('poiHeading', models.DecimalField(decimal_places=4, max_digits=9)),
                ('poiAltitude', models.DecimalField(decimal_places=4, max_digits=9)),
                ('flags', models.IntegerField()),
                ('photo', models.IntegerField()),
                ('panoSectorsCount', models.IntegerField()),
                ('panoDeltaAngle', models.DecimalField(decimal_places=4, max_digits=9)),
                ('poiPitch', models.DecimalField(decimal_places=4, max_digits=9)),
                ('poiRoll', models.DecimalField(decimal_places=4, max_digits=9)),
                ('type', models.IntegerField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone_missions_logs.ydmission')),
            ],
            options={
                'db_table': 'yd_drone_mission_point',
            },
        ),
        migrations.CreateModel(
            name='YDLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='logs/')),
                ('flight_data', models.DateTimeField()),
                ('description', models.TextField()),
                ('at_create', models.DateTimeField()),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drone_missions_logs.ydmission')),
            ],
            options={
                'db_table': 'yd_drone_logs_file',
            },
        ),
    ]
