# Generated by Django 3.2.8 on 2022-01-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone_missions_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YDMission',
            new_name='Mission',
        ),
        migrations.AlterModelTable(
            name='mission',
            table='drone_missions',
        ),
    ]
