# Generated by Django 3.2.8 on 2022-01-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone_missions_logs', '0002_auto_20220122_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YDLogFile',
            new_name='LogFile',
        ),
    ]
