# Generated by Django 3.2.8 on 2022-01-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_missions_logs', '0003_rename_ydlogfile_logfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='protocol_type',
            field=models.CharField(choices=[('ML', 'MavLink'), ('PX4', 'PX4'), ('YD', 'VorobyovYD')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='mission',
            name='protocol_type',
            field=models.CharField(choices=[('ML', 'MavLink'), ('PX4', 'PX4'), ('YD', 'VorobyovYD')], default='', max_length=3),
        ),
        migrations.AlterModelTable(
            name='logfile',
            table='drone_logs_file',
        ),
    ]
