# Generated by Django 3.2.8 on 2022-01-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_missions_logs', '0004_auto_20220122_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='MavLinkMissionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param1', models.DecimalField(decimal_places=9, max_digits=15)),
                ('param2', models.DecimalField(decimal_places=9, max_digits=15)),
                ('param3', models.DecimalField(decimal_places=9, max_digits=15)),
                ('param4', models.DecimalField(decimal_places=9, max_digits=15)),
                ('x', models.DecimalField(decimal_places=9, max_digits=15)),
                ('y', models.DecimalField(decimal_places=9, max_digits=15)),
                ('z', models.DecimalField(decimal_places=9, max_digits=15)),
                ('seq', models.IntegerField()),
                ('command', models.IntegerField()),
                ('target_component', models.IntegerField()),
                ('frame', models.IntegerField()),
                ('current', models.IntegerField()),
                ('autocontinue', models.IntegerField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone_missions_logs.mission')),
            ],
            options={
                'db_table': 'mavlink_drone_mission_point',
            },
        ),
    ]
